import {load} from 'cheerio';
import {createHash} from 'node:crypto';
// Only these fixed official pages may be fetched. No user-supplied URLs or redirects.
export const SOURCES=[{id:'mcdonalds',url:'https://www.mcdonalds.com/us/en-us/deals.html',brand:'McDonald’s',anchors:['McValue','Meal Deals']},{id:'chilis',url:'https://www.chilis.com/3-for-me',brand:'Chili’s',anchors:['3 for Me','10.99']},{id:'applebees',url:'https://www.applebees.com/en/specials',brand:'Applebee’s',anchors:['Specials','entrées']}];
export function sourceText(html){const $=load(html);$('script,style,nav,header,footer,noscript,iframe,svg').remove();return($('main').length?$('main').text():$('body').text()).replace(/\s+/g,' ').trim();}
export function fingerprint(text){return createHash('sha256').update(text).digest('hex')}
export async function inspectSource(source){const response=await fetch(source.url,{redirect:'error',signal:AbortSignal.timeout(8000),headers:{'User-Agent':'MealRadar/1.0 (offer verification)','Accept':'text/html'}});if(!response.ok)throw new Error(`Official page returned ${response.status}`);if(!response.headers.get('content-type')?.includes('text/html'))throw new Error('Source did not return HTML');const reader=response.body.getReader();let size=0;const chunks=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>2_000_000){await reader.cancel();throw new Error('Source exceeds size limit')}chunks.push(Buffer.from(value))}const text=sourceText(Buffer.concat(chunks).toString());if(text.length<200||!source.anchors.every(a=>text.toLowerCase().includes(a.toLowerCase()))||/verify you are human|access denied|checking your browser/i.test(text))throw new Error('Official content could not be verified');return{hash:fingerprint(text),text};}
export async function checkSources(db){const outcomes=[];for(const source of SOURCES){const checkedAt=new Date().toISOString();let hash=null,status='unavailable';try{const result=await inspectSource(source);hash=result.hash;const{data,error}=await db.from('source_checks').select('approved_hash').eq('id',source.id).maybeSingle();if(error)throw error;status=data?.approved_hash===hash?'unchanged':data?.approved_hash?'changed':'needs_review';}catch{status='unavailable'}
 const{error:writeError}=await db.from('source_checks').upsert({id:source.id,url:source.url,last_hash:hash,last_status:status,last_checked_at:checkedAt},{onConflict:'id'});if(writeError)throw writeError;
 if(status==='unchanged'){const{error}=await db.from('deals').update({checked_at:checkedAt}).eq('source_url',source.url).eq('status','verified');if(error)throw error;}else if(status==='changed'){const{error}=await db.from('deals').update({status:'check'}).eq('source_url',source.url).eq('status','verified');if(error)throw error;}
 outcomes.push({id:source.id,status});}return outcomes;}
